pool:
    vmImage: ubuntu-latest

trigger:
    - master

steps:
    - checkout: self

    - task: "Npm@1"
      displayName: "install"
      inputs:
          command: "install"
          verbose: false

    - task: "Npm@1"
      displayName: "check"
      inputs:
          command: custom
          verbose: false
          customCommand: "run check"

    - task: "Npm@1"
      displayName: "build"
      inputs:
          command: custom
          verbose: false
          customCommand: "run build"

    - task: CopyFiles@2
      displayName: "copy package.json"
      inputs:
          contents: package.json
          targetFolder: ./dist

    - task: "Npm@1"
      displayName: "publish"
      inputs:
          command: publish
          workingDir: ./dist
          publishRegistry: useFeed
          publishFeed: WebXR/WebXR
